# Form implementation generated from reading ui file '.\mainformdsb.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainFormDsb(object):
    def setupUi(self, MainFormDsb):
        MainFormDsb.setObjectName("MainFormDsb")
        MainFormDsb.resize(450, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFormDsb.sizePolicy().hasHeightForWidth())
        MainFormDsb.setSizePolicy(sizePolicy)
        MainFormDsb.setMinimumSize(QtCore.QSize(450, 450))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainFormDsb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_vertical_layout = QtWidgets.QVBoxLayout()
        self.main_vertical_layout.setObjectName("main_vertical_layout")
        self.btn_select_roi = QtWidgets.QPushButton(MainFormDsb)
        self.btn_select_roi.setObjectName("btn_select_roi")
        self.main_vertical_layout.addWidget(self.btn_select_roi)
        self.vis_widget = QtInteractor(MainFormDsb)
        self.vis_widget.setObjectName("vis_widget")
        self.main_vertical_layout.addWidget(self.vis_widget)
        self.sldr_neck_point = QtWidgets.QSlider(MainFormDsb)
        self.sldr_neck_point.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sldr_neck_point.setObjectName("sldr_neck_point")
        self.main_vertical_layout.addWidget(self.sldr_neck_point)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_save_head = QtWidgets.QPushButton(MainFormDsb)
        self.btn_save_head.setObjectName("btn_save_head")
        self.horizontalLayout.addWidget(self.btn_save_head)
        self.btn_discard_head = QtWidgets.QPushButton(MainFormDsb)
        self.btn_discard_head.setObjectName("btn_discard_head")
        self.horizontalLayout.addWidget(self.btn_discard_head)
        self.main_vertical_layout.addLayout(self.horizontalLayout)
        self.main_vertical_layout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.main_vertical_layout)
        self.lbl_status = QtWidgets.QLabel(MainFormDsb)
        self.lbl_status.setText("")
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout.addWidget(self.lbl_status)

        self.retranslateUi(MainFormDsb)
        QtCore.QMetaObject.connectSlotsByName(MainFormDsb)

    def retranslateUi(self, MainFormDsb):
        _translate = QtCore.QCoreApplication.translate
        MainFormDsb.setWindowTitle(_translate("MainFormDsb", "Form"))
        self.btn_select_roi.setText(_translate("MainFormDsb", "Select ROI"))
        self.btn_save_head.setText(_translate("MainFormDsb", "Save Head"))
        self.btn_discard_head.setText(_translate("MainFormDsb", "Discard Head"))
from pyvistaqt import QtInteractor


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormDsb = QtWidgets.QWidget()
    ui = Ui_MainFormDsb()
    ui.setupUi(MainFormDsb)
    MainFormDsb.show()
    sys.exit(app.exec())
