# Form implementation generated from reading ui file '.\mainformdsb.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainFormDsb(object):
    def setupUi(self, MainFormDsb):
        MainFormDsb.setObjectName("MainFormDsb")
        MainFormDsb.resize(450, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFormDsb.sizePolicy().hasHeightForWidth())
        MainFormDsb.setSizePolicy(sizePolicy)
        MainFormDsb.setMinimumSize(QtCore.QSize(450, 450))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainFormDsb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_select_roi = QtWidgets.QPushButton(MainFormDsb)
        self.btn_select_roi.setObjectName("btn_select_roi")
        self.verticalLayout.addWidget(self.btn_select_roi)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vtk_widget = QtInteractor(MainFormDsb)
        self.vtk_widget.setObjectName("vtk_widget")
        self.verticalLayout_2.addWidget(self.vtk_widget)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(MainFormDsb)
        QtCore.QMetaObject.connectSlotsByName(MainFormDsb)

    def retranslateUi(self, MainFormDsb):
        _translate = QtCore.QCoreApplication.translate
        MainFormDsb.setWindowTitle(_translate("MainFormDsb", "Form"))
        self.btn_select_roi.setText(_translate("MainFormDsb", "Select ROI"))
from pyvistaqt import QtInteractor


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormDsb = QtWidgets.QWidget()
    ui = Ui_MainFormDsb()
    ui.setupUi(MainFormDsb)
    MainFormDsb.show()
    sys.exit(app.exec())
