# Form implementation generated from reading ui file '.\mainformdsb.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainFormDsb(object):
    def setupUi(self, MainFormDsb):
        MainFormDsb.setObjectName("MainFormDsb")
        MainFormDsb.resize(418, 264)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFormDsb.sizePolicy().hasHeightForWidth())
        MainFormDsb.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainFormDsb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=MainFormDsb)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.ccb_dendrite_mesh_preprocessing = OrsObjectClassComboBox(parent=MainFormDsb)
        self.ccb_dendrite_mesh_preprocessing.setMinimumSize(QtCore.QSize(0, 26))
        self.ccb_dendrite_mesh_preprocessing.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ccb_dendrite_mesh_preprocessing.setObjectName("ccb_dendrite_mesh_preprocessing")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ccb_dendrite_mesh_preprocessing)
        self.btn_select_dsb_output = QtWidgets.QPushButton(parent=MainFormDsb)
        self.btn_select_dsb_output.setObjectName("btn_select_dsb_output")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.btn_select_dsb_output)
        self.line_dsb_output = QtWidgets.QLineEdit(parent=MainFormDsb)
        self.line_dsb_output.setObjectName("line_dsb_output")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_dsb_output)
        self.chk_psd_annotation = QtWidgets.QCheckBox(parent=MainFormDsb)
        self.chk_psd_annotation.setObjectName("chk_psd_annotation")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chk_psd_annotation)
        self.ccb_psd_annotation = OrsObjectClassComboBox(parent=MainFormDsb)
        self.ccb_psd_annotation.setMinimumSize(QtCore.QSize(0, 26))
        self.ccb_psd_annotation.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ccb_psd_annotation.setObjectName("ccb_psd_annotation")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ccb_psd_annotation)
        self.chk_psd_multiroi = QtWidgets.QCheckBox(parent=MainFormDsb)
        self.chk_psd_multiroi.setObjectName("chk_psd_multiroi")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chk_psd_multiroi)
        self.ccb_psd_multiroi = OrsObjectClassComboBox(parent=MainFormDsb)
        self.ccb_psd_multiroi.setMinimumSize(QtCore.QSize(0, 26))
        self.ccb_psd_multiroi.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ccb_psd_multiroi.setObjectName("ccb_psd_multiroi")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ccb_psd_multiroi)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.btn_preprocessing_run = QtWidgets.QPushButton(parent=MainFormDsb)
        self.btn_preprocessing_run.setObjectName("btn_preprocessing_run")
        self.verticalLayout_2.addWidget(self.btn_preprocessing_run)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.lbl_status = QtWidgets.QLabel(parent=MainFormDsb)
        self.lbl_status.setText("")
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout.addWidget(self.lbl_status)

        self.retranslateUi(MainFormDsb)
        QtCore.QMetaObject.connectSlotsByName(MainFormDsb)

    def retranslateUi(self, MainFormDsb):
        _translate = QtCore.QCoreApplication.translate
        MainFormDsb.setWindowTitle(_translate("MainFormDsb", "DSB"))
        self.label.setText(_translate("MainFormDsb", "Dendrite Mesh"))
        self.btn_select_dsb_output.setText(_translate("MainFormDsb", "Select DSB Output"))
        self.chk_psd_annotation.setText(_translate("MainFormDsb", "PSD Annotation"))
        self.chk_psd_multiroi.setText(_translate("MainFormDsb", "PSD MultiROI"))
        self.btn_preprocessing_run.setText(_translate("MainFormDsb", "Run"))
from ORSServiceClass.ORSWidget.orsobjectclasscombobox.orsobjectclasscombobox import OrsObjectClassComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormDsb = QtWidgets.QWidget()
    ui = Ui_MainFormDsb()
    ui.setupUi(MainFormDsb)
    MainFormDsb.show()
    sys.exit(app.exec())
